name: Build and Push EURAXESS MCP

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write   # wichtig, wenn du GHCR mit GITHUB_TOKEN benutzen willst

concurrency:
  group: build-euraxess-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./euraxess
          push: true
          platforms: linux/amd64,linux/arm64      # optional: entferne, wenn nicht benötigt
          tags: |
            ghcr.io/${{ secrets.REGISTRY_USER }}/euraxess-mcp:latest
            ghcr.io/${{ secrets.REGISTRY_USER }}/euraxess-mcp:${{ github.sha }}
          # optional: cache-from / cache-to (speichert layers in registry)
          cache-from: type=registry,ref=ghcr.io/${{ secrets.REGISTRY_USER }}/euraxess-mcp:cache
          cache-to: type=registry,ref=ghcr.io/${{ secrets.REGISTRY_USER }}/euraxess-mcp:cache,mode=max
