name: Build and Push EURAXESS MCP

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

concurrency:
  group: build-euraxess-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set owner lowercased
        id: set_owner
        run: |
          # GITHUB_REPOSITORY ist "owner/repo"
          OWNER="${GITHUB_REPOSITORY%%/*}"
          OWNER_LOWER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          echo "OWNER=$OWNER" >> $GITHUB_ENV
          echo "OWNER_LOWER=$OWNER_LOWER" >> $GITHUB_ENV
        # setzt env. OWNER and OWNER_LOWER for later steps

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR using GITHUB_TOKEN
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./euraxess
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/euraxess-mcp:latest
            ghcr.io/${{ env.OWNER_LOWER }}/euraxess-mcp:${{ github.sha }}
